# Generated by Django 4.2.1 on 2023-05-09 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_alter_exam_slug_alter_question_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('slug', 'exam')},
        ),
    ]
