# Generated by Django 4.2.1 on 2023-07-15 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_alter_question_unique_together_alter_exam_slug_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('name', 'exam')},
        ),
    ]
