# Generated by Django 4.2.1 on 2023-07-15 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_alter_question_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='avaliable',
            new_name='available',
        ),
    ]
