# Generated by Django 4.2.1 on 2023-07-15 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0013_exam_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
