# Generated by Django 4.2.1 on 2023-07-16 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0014_alter_exam_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='code',
            field=models.CharField(editable=False, max_length=6, unique=True),
        ),
    ]
