# Generated by Django 4.2.1 on 2023-07-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0020_alter_question_max_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='max_score',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
