# Generated by Django 4.2.1 on 2023-07-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0022_alter_question_max_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='modified',
            field=models.BooleanField(default=False),
        ),
    ]
