# Generated by Django 4.2.1 on 2023-07-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0023_question_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='modified',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
