# Generated by Django 4.2.1 on 2023-07-24 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0027_alter_exam_name_alter_exam_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together=set(),
        ),
    ]
